import Layout from "@/components/Layout";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Application({
  Component,
  pageProps,
}: {
  Component: React.FC;
  pageProps: {};
}) {
  return (
    <Layout>
      <Component {...pageProps} />
    </Layout>
  );
}
