import "../styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Application({
  Component,
  pageProps,
}: {
  Component: React.FC;
  pageProps: {};
}) {
  return (
    <main className={inter.className}>
      <Component {...pageProps} />
    </main>
  );
}
