import Layout from "@/components/Layout";
import { ChakraProvider, ColorModeScript } from "@chakra-ui/react";
import theme from "../styles/theme";
import "@fontsource/dm-sans";
import "@fontsource/poppins";
import { AppWrapper } from "@/context/state";
import { NextRouter } from "next/router";
import { motion, AnimatePresence } from "framer-motion";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Application({
  Component,
  pageProps,
  router,
}: {
  Component: React.FC;
  pageProps: {};
  router: NextRouter;
}) {
  const pageVariants = {
    pageInitial: {
      opacity: 0,
      x: "100%",
    },
    pageAnimate: {
      opacity: 1,
      x: 0,
    },
    pageExit: {
      opacity: 0,
      x: "-100%",
    },
  };

  return (
    <ChakraProvider theme={theme}>
      <AppWrapper>
        <ColorModeScript
          initialColorMode={theme.colorConfig.initialColorMode}
        />
        <Layout>
          <AnimatePresence mode="wait">
            <motion.div
              key={router.route}
              initial="pageInitial"
              animate="pageAnimate"
              exit="pageExit"
              variants={pageVariants}
              transition={{
                type: "spring",
                duration: 0.7,
                bounce: 0.4
              }}
            >
              <Component {...pageProps} />
            </motion.div>
          </AnimatePresence>
        </Layout>
      </AppWrapper>
    </ChakraProvider>
  );
}
